name: Daily Cloudflare Deploy
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Cloudflare Deploy
              run: |
                curl -X POST "$CLOUDFLARE_DEPLOY_HOOK"
                env: CLOUDFLARE_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
            